In [3]:
import numpy as np

In [4]:
a=np.array([[1,2,2],
           [5,7,9],
           [7,2,6]])

In [5]:
a

array([[1, 2, 2],
       [5, 7, 9],
       [7, 2, 6]])

In [6]:
print(a)

[[1 2 2]
 [5 7 9]
 [7 2 6]]


In [8]:
a[1:2,1:2]

array([[7]])

In [11]:
a[1:,1:]

array([[7, 9],
       [2, 6]])

In [21]:
arr=np.arange(0,9).reshape(3,3)

In [22]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
b=np.arange(0,9,2)

In [24]:
b

array([0, 2, 4, 6, 8])

In [76]:
c=np.linspace(0,10,10,endpoint=False,retstep=False,dtype=int)

In [77]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
d=c.copy()

In [79]:
d[5:]=500

In [80]:
d

array([  0,   1,   2,   3,   4, 500, 500, 500, 500, 500])

In [81]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
c<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [91]:
e=np.ones(8,int)

In [92]:
e

array([1, 1, 1, 1, 1, 1, 1, 1])

In [95]:
type(np.random.rand(1,3))

numpy.ndarray

In [96]:
np.random.rand(3,3)

array([[0.56137169, 0.12001923, 0.84875726],
       [0.18395457, 0.93862298, 0.02180393],
       [0.78320968, 0.75727024, 0.79288054]])

In [97]:
np.random.randn(3,3)

array([[-0.44519093,  1.48023725,  0.00425168],
       [ 1.36555702,  2.60034414,  0.79825934],
       [-2.16534301, -1.29260681, -0.91804   ]])

In [109]:
np.random.randn(2,2,4)

array([[[ 0.1719286 , -0.34086783, -2.12645347, -0.92999355],
        [ 0.35114491, -0.53066012,  0.5029953 , -0.15417666]],

       [[ 0.13086328, -0.00365757,  0.74082904, -0.18653869],
        [ 1.52846388, -0.56337998, -0.10054512, -0.56477476]]])

In [113]:
np.random.random_sample((2,3))

array([[0.29324577, 0.13101207, 0.77386231],
       [0.32866946, 0.49694487, 0.48317251]])

In [115]:
import pandas as pd

In [116]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['R1','R2','R3','R4','R5'],columns=['C1','C2','C3','C4'])

In [119]:
df.head()

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [120]:
df.loc['R1']

C1    0
C2    1
C3    2
C4    3
Name: R1, dtype: int32

In [125]:
type(df.loc['R1'])

pandas.core.series.Series

In [127]:
df.loc[['R1','R2']]

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7

In [128]:
type(df.loc[['R1','R2']])

pandas.core.frame.DataFrame

In [129]:
df.to_csv('random_num.csv')

In [130]:
df.iloc[2:4,1:3]

C2  C3
R3   9  10
R4  13  14

In [131]:
df.iloc[2:4,1:3].values

array([[ 9, 10],
       [13, 14]])

In [136]:
df['C1'].value_counts()

12    1
4     1
16    1
8     1
0     1
Name: C1, dtype: int64

In [140]:
df['C1'].values

array([ 0,  4,  8, 12, 16])

In [141]:
df.isnull().sum()

C1    0
C2    0
C3    0
C4    0
dtype: int64

In [142]:
df.isnull()

C1     C2     C3     C4
R1  False  False  False  False
R2  False  False  False  False
R3  False  False  False  False
R4  False  False  False  False
R5  False  False  False  False

In [143]:
df.sum()

C1    40
C2    45
C3    50
C4    55
dtype: int64

In [148]:
pk=pd.read_csv('random_num.csv')

In [149]:
pk.head()

Unnamed: 0  C1  C2  C3  C4
0         R1   0   1   2   3
1         R2   4   5   6   7
2         R3   8   9  10  11
3         R4  12  13  14  15
4         R5  16  17  18  19

In [151]:
df['C2'].unique()

array([ 1,  5,  9, 13, 17])